### ISSUE TITLE
Rev 10272 also broken (on Linux)

### ISSUE THREAD

**Issue by mori151** [jgscripts/fivem-artifacts-db#2]
Hello, I am using jg-advancedgarages, which was released on 2024-10-03, on Linux with FiveM (txAdmin).

The issue is that when I set `Config.SpawnVehiclesWithServerSetter = true`, on FiveM revision 10272, the following error occurs on the server side, preventing vehicles from being spawned from the garage:
`Vehicle props failed to set after trying several times. First check if the plate within the vehicle props JSON does not match the plate column.`

I have confirmed that with the same plugin and database, this issue does not occur on revision 9868.

**Comment by jrgrimshaw** [comment]
Hey! I'm not sure why it's working for you on the 9x artifacts and not on the latest. Server spawning in general is a bit temperamental for some people hence why we have the option to turn it off. I will keep an eye on this but it seems to be working fine for me and the staff team on the new artifacts. 

This being said—it could be due to something within Linux. I will do some testing there.

**Comment by mori151** [comment]
Thank you for your response. I see, in that case, it does seem likely that it could be a Linux-related issue.

Even with the option to disable it, there were instances where it seemed like the plate information wasn’t being retrieved correctly, leading to situations where the vehicle's damage level didn’t change. (Apologies, I forgot the exact error message, but similar issues occurred even with standalone plugins like jim-mechanic.)

I really appreciate your investigation. Thank you for your help!

**Comment by jrgrimshaw** [comment]
@mori151 We are starting to get some reports from almost all artifacts since 10272. I've added the artifact range `10268-10309` until we have more info on what issues are in these releases, and how to potentially solve them.
